import java.util.*;
public class intersectionOfTwoArrays {

	public static void main(String[] args) {
		// TODO Autogenerated method stub
		int[] nums1 = {1,1,2,2};
		int[] nums2 = {2,2};
		
		System.out.println(intersection(nums1, nums2));
	}
	
	public static String intersection(int[] nums1, int[] nums2) {
		if(nums1.length == 0 || nums2.length == 0) {
			return Arrays.toString(new int[] {});
		}
		Arrays.sort(nums1);
		Arrays.sort(nums2);
		
		int i = 0;
		int j = 0;
		
		Set<Integer> commonNums = new HashSet<>();
		
		
		
		while(i < nums1.length && j < nums2.length) {
			if(nums1[i] == nums2[j]) {
				commonNums.add(nums1[i]);
				i++;
				j++;
				continue;
			}
			
			else if(nums1[i] > nums2[j]) {
				j++;
				continue;
			}
			
			else if(nums2[j] > nums1[i]) {
				i++;
				continue;
			}
			
			
		}
		
		int[] result = new int[commonNums.size()];
		int p = 0;
		for(int num: commonNums) {
			result[p++] = num;
		}
		return Arrays.toString(result);
	}

}
